# Generated by Django 5.1.7 on 2025-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_id_alter_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='current_medications',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
